use Final;
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (1, 'JTM116', 'Sp20', '005', 'Graspus graspus', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (2, 'XOP487', 'Fa20', '007', 'Gazella granti', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (3, 'GLG247', 'Fa20', '006', 'Chelodina longicollis', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (4, 'CTH551', 'Sp20', '005', 'Bison bison', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (5, 'LVN264', 'Fa20', '005', 'Lepus arcticus', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (6, 'XCM545', 'Sp20', '008', 'Crotalus adamanteus', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (7, 'GFZ441', 'Fa20', '001', 'Phalacrocorax carbo', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (8, 'GGB678', 'Fa20', '003', 'Paraxerus cepapi', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (9, 'FFZ016', 'Fa20', '001', 'Tyto novaehollandiae', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (10, 'VEU144', 'Sp20', '001', 'Leptoptilos crumeniferus', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (11, 'SVX163', 'Fa20', '002', 'Uraeginthus granatina', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (12, 'VCB355', 'Fa20', '009', 'Ovis dalli stonei', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (13, 'AAB518', 'Sp20', '002', 'Francolinus coqui', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (14, 'XFF785', 'Fa20', '000', 'Cervus elaphus', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (15, 'ZIF184', 'Fa20', '009', 'Anthropoides paradisea', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (16, 'HEO092', 'Sp20', '001', 'Dendrocitta vagabunda', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (17, 'MOK484', 'Sp20', '004', 'Tamiasciurus hudsonicus', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (18, 'BDT397', 'Sp20', '004', 'Corvus brachyrhynchos', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (19, 'NMG396', 'Fa20', '008', 'Francolinus leucoscepus', 'Inactive');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description, C_Status) values (20, 'NQQ382', 'Fa20', '005', 'Phalacrocorax carbo', 'Inactive');
call new_class('CS410', 'Sp20', 1, 'Databases');
call select_class('CS410');
call Final.add_category('Homework', 35);
call Final.add_category('Final Project', 15);
call Final.add_category('Midterm 1', 15);
call Final.add_category('Midterm 2', 15);
call Final.add_category('Final', 20);
call Final.add_assignment('Assignment 2', 'Homework', 'Set up Database', 80);
call Final.add_assignment('Assignment 3', 'Homework', 'Basic Queries', 100);
call Final.add_assignment('Assignment 4', 'Homework', 'Difficult Queries', 80);
call Final.add_assignment('Midterm 1', 'Midterm 1', 'First midterm', 100);
call Final.add_assignment('Midterm 2', 'Midterm 2', 'Second midterm', 100);
call Final.add_student('aubreybohn', 101, 'Spannagel', 'Aubrey');
call Final.add_student('samanthamaxey299', 102, 'Maxey', 'Samantha');
call Final.grade('Assignment 2', 'aubreybohn', 77);
call Final.grade('Assignment 3', 'aubreybohn', 100);
call Final.grade('Assignment 4', 'aubreybohn', 75);
call Final.grade('Midterm 1', 'aubreybohn', 88);
call Final.grade('Midterm 2', 'aubreybohn', 79);
call Final.grade('Assignment 2', 'samanthamaxey299', 80);
call Final.grade('Assignment 3', 'samanthamaxey299', 90);
call Final.grade('Assignment 4', 'samanthamaxey299', 80);
call Final.grade('Midterm 1', 'samanthamaxey299', 88);
call Final.grade('Midterm 2', 'samanthamaxey299', 93);

