use Final;
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (1, 'JTM116', 'Sp20', '005', 'Graspus graspus');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (2, 'XOP487', 'Fa20', '007', 'Gazella granti');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (3, 'GLG247', 'Fa20', '006', 'Chelodina longicollis');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (4, 'CTH551', 'Sp20', '005', 'Bison bison');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (5, 'LVN264', 'Fa20', '005', 'Lepus arcticus');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (6, 'XCM545', 'Sp20', '008', 'Crotalus adamanteus');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (7, 'GFZ441', 'Fa20', '001', 'Phalacrocorax carbo');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (8, 'GGB678', 'Fa20', '003', 'Paraxerus cepapi');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (9, 'FFZ016', 'Fa20', '001', 'Tyto novaehollandiae');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (10, 'VEU144', 'Sp20', '001', 'Leptoptilos crumeniferus');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (11, 'SVX163', 'Fa20', '002', 'Uraeginthus granatina');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (12, 'VCB355', 'Fa20', '009', 'Ovis dalli stonei');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (13, 'AAB518', 'Sp20', '002', 'Francolinus coqui');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (14, 'XFF785', 'Fa20', '000', 'Cervus elaphus');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (15, 'ZIF184', 'Fa20', '009', 'Anthropoides paradisea');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (16, 'HEO092', 'Sp20', '001', 'Dendrocitta vagabunda');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (17, 'MOK484', 'Sp20', '004', 'Tamiasciurus hudsonicus');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (18, 'BDT397', 'Sp20', '004', 'Corvus brachyrhynchos');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (19, 'NMG396', 'Fa20', '008', 'Francolinus leucoscepus');
insert into Class (Class_ID, Course_Number, Term, Section_Number, C_Description) values (20, 'NQQ382', 'Fa20', '005', 'Phalacrocorax carbo');